name: Terraform AWS Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-AWS-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Info
        run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
          echo "Running on a ${{ runner.os }} server hosted by GitHub."
          echo "Branch on ${{ github.ref }} | Repository from ${{ github.repository }}."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::590184123501:role/iam-role-github
          aws-region: ap-southeast-1

      - name: Check Out Repository Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Print Job Status
        run: echo "Job status is ${{ job.status }}."